"""Smoke tests for the CLI and the autogenerated solver subcommands."""

from pathlib import Path

from click.testing import CliRunner

from enclose_horse_solver.cli import cli


def test_default_solver_runs_on_test2(tmp_path: Path) -> None:
    runner = CliRunner()
    # Use the bundled all-grass board with 12 walls.
    result = runner.invoke(cli, ["solve", "-w", "12", "test2.txt"])
    assert result.exit_code == 0, result.output
    assert "Max Score: 12" in result.output


def test_registered_solver_subcommand_runs() -> None:
    runner = CliRunner()
    result = runner.invoke(
        cli,
        ["solve", "-w", "12", "test2.txt", "costly-walls", "-c", "0"],
    )
    assert result.exit_code == 0, result.output
    assert "costly-walls" in result.output
    assert "Max Score: 12" in result.output


def test_unknown_solver_subcommand_fails() -> None:
    runner = CliRunner()
    result = runner.invoke(cli, ["solve", "-w", "12", "test2.txt", "nope"])
    assert result.exit_code != 0
